force-app/main/default/objects/eSign_Request__c/eSign_Request__c.object-meta.xml
<CustomObject>
    <label>eSign Request</label>
    <nameField>
        <label>eSign Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>eSign Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/eSign_Request__c/fields/Sent_On__c.field-meta.xml
<CustomField>
    <fullName>Sent_On__c</fullName>
    <label>Sent On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/eSign_Request__c/fields/Sent_to__c.field-meta.xml
<CustomField>
    <fullName>Sent_to__c</fullName>
    <label>Sent to</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/eSign_Request__c/fields/Signing_Status__c.field-meta.xml
<CustomField>
    <fullName>Signing_Status__c</fullName>
    <label>Signing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Not Signed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ESignRequestController.cls
public class ESignRequestController {
    
    @AuraEnabled(cacheable = true)
    public static List<eSign_Request__c> getRequests(Integer pageSize, Integer pageNumber){
        Integer limitSize = (pageSize == null || pageSize < 1) ? 10 : pageSize;
        Integer page = (pageNumber == null || pageNumber < 1) ? 1 : pageNumber;
        Integer offsetRows = (page - 1) * limitSize;
        
        return [SELECT Id, Name, Sent_to__c, Signing_Status__c, Sent_On__c FROM eSign_Request__c 
                WITH USER_MODE 
                ORDER BY Sent_On__c DESC 
                LIMIT :limitSize OFFSET :offsetRows
               ];
    }
    
    @AuraEnabled(cacheable = true)
    public static Integer getCounts(){
        return [SELECT COUNT() FROM eSign_Request__c WITH USER_MODE];
    }

}